#!/bin/sh
#
# Import given txt-files into dayone
# Files are generated by IFTTT-service
#
# Author: Stefan Zweifel <https://stefanzweifel.io>

# Modify the following variable to your needs. The folder should only contain log-files
LOGDIR='up-logs/'

###############################
# DO NOT EDIT BELOW THIS LINE #
###############################

cd $LOGDIR;

for D in *; do

    echo "Read file:" $D;

    DATE=$( echo $D | cut -d'-' -f 1;)
    MONTH=$( echo $D | cut -d'_' -f 1;)
    DAY=$( echo $D | cut -d'_' -f 2;)
    YEAR=$( echo $DATE | tail -c 5;)

    # Add to Dayone
    dayone -d="$MONTH/$DAY/$YEAR" new < $D

    # Remove File from Disk
    rm $D

done

echo "Done!"